version: '2'
services:
  gameroom:
    build: 
      context: gameroom/
      dockerfile: Dockerfile
    # image: coreykruger/gameroom
    ports:
      - "3334:3334"
    container_name: gameroom_server
  shapeshift:
    build: 
      context: shapeshift/
      dockerfile: Dockerfile
      args:
        # GAMEROOM_HOST: "45.79.101.197" # "ec2-52-39-48-191.us-west-2.compute.amazonaws.com"
        GAMEROOM_HOST: "192.168.99.100"
    ports:
      - "8001:8001"
    links:
      - gameroom
    container_name: shapeshift_webpage
  # consul:
  #   image: consul